<?php
/**
* File Name: pied-page.inc
* author: alexandre trudelle
*/
?>
</section>
<section id="baspage" >


</section>
<!--/#bottom-->

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="social">
                    <ul class="social-share">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--/.container-->
</div>
<!--/.top-bar-->

<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; Gp Theme. All Rights Reserved.<br>
                Site Web par Alexandre Trudelle <?php
                echo date("Y")
                ?>


                <div class="credits">
                    <!--
                      All the links in the footer should remain intact.
                      You can delete the links only if you purchased the pro version.
                      Licensing information: https://bootstrapmade.com/license/
                      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Gp
                    -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="../index.php">Accueil</a></li>
                    <li><a href="../horaire.php">Horaire</a></li>
                    <li><a href="#">Dates importantes</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
            <script src="/js/jquery.js"></script>
            <script src="/js/bootstrap.min.js"></script>
            <script src="/js/jquery.prettyPhoto.js"></script>
            <script src="/js/jquery.isotope.min.js"></script>
            <script src="/js/wow.min.js"></script>
            <script src="/js/main.js"></script>
        </div>
    </div>
</footer>
</body>
</html>
